package com.slick.tactical.app

import android.util.Log
import io.sentry.Sentry
import io.sentry.SentryEvent
import io.sentry.SentryLevel
import io.sentry.protocol.Message
import timber.log.Timber

/**
 * Production Timber tree that routes WARN and ERROR logs to Sentry.
 *
 * Security guarantees:
 * - Only WARN (priority 5) and ERROR (priority 6) reach Sentry -- DEBUG and INFO are dropped.
 * - GPS coordinates are redacted before transmission (matches [COORD_PATTERN]).
 * - Rider IDs (short UUID fragments) are redacted.
 * - No PII fields are added to Sentry scope (no device name, no user ID).
 *
 * Musk Protocol: zero unnecessary overhead. No INFO spam in production.
 * Security Protocol: no PII in logs. Coordinates → [GPS_REDACTED].
 */
class SlickCrashTree : Timber.Tree() {

    companion object {
        // Matches decimal GPS coordinates: -27.4698 or 153.0251 (4+ decimal places)
        private val COORD_PATTERN = Regex("""-?\d{1,3}\.\d{4,}""")
        // Matches short ephemeral rider IDs (8 hex chars, as generated by UUID.take(8))
        private val RIDER_ID_PATTERN = Regex("""\b[0-9a-f]{8}\b""")
    }

    override fun isLoggable(tag: String?, priority: Int): Boolean {
        // Only WARN and ERROR reach Sentry in production.
        // DEBUG and INFO are discarded -- they're too verbose and may contain PII.
        return priority >= Log.WARN
    }

    override fun log(priority: Int, tag: String?, message: String, t: Throwable?) {
        val sanitized = sanitize(message)
        val level = priority.toSentryLevel()

        if (t != null) {
            // Exceptions: capture with full stack trace + sanitized log message as extra context
            Sentry.captureEvent(
                SentryEvent(t).apply {
                    this.level = level
                    this.message = Message().apply { this.message = "[$tag] $sanitized" }
                    // No user, no device extras, no GPS data
                },
            )
        } else {
            // Non-exception WARN/ERROR: capture as Sentry message
            Sentry.captureMessage("[$tag] $sanitized", level)
        }
    }

    /**
     * Removes GPS coordinates and ephemeral IDs from a log message before it leaves the device.
     *
     * Examples:
     * - "GPS fix: -27.4698, 153.0251" → "GPS fix: [GPS_REDACTED], [GPS_REDACTED]"
     * - "riderId=a1b2c3d4 joined" → "riderId=[RIDER_REDACTED] joined"
     */
    private fun sanitize(message: String): String = message
        .replace(COORD_PATTERN, "[GPS_REDACTED]")
        .replace(RIDER_ID_PATTERN, "[RIDER_REDACTED]")

    private fun Int.toSentryLevel(): SentryLevel = when (this) {
        Log.WARN -> SentryLevel.WARNING
        Log.ERROR -> SentryLevel.ERROR
        Log.ASSERT -> SentryLevel.FATAL
        else -> SentryLevel.INFO
    }
}
